ktor:
    application:
        modules:
            - com.ggr3ml1n.presentation.main.ApplicationKt.module
    deployment:
        port: 8080

jwt:
    domain: "https://localhost/"
    audience: "rest-test"
    realm: "rest test"
    secret: "some secret"